name: Build image

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 16

    - name: Install bower
      run: npm install -g bower
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 3.1.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --no-restore -c Release -o ${{ github.workspace }}/publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with: 
        name: DiscordMafia
        path: |
          ${{ github.workspace }}/publish
          ${{ github.workspace }}/docker/*.Dockerfile

  docker-bot:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: DiscordMafia

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        id: builder-bot

      - uses: docker/setup-buildx-action@v3
        id: builder-web

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get SHA hash
        uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Build bot
        uses: docker/build-push-action@v5.1.0
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          builder: ${{ steps.builder-bot.outputs.name }}
          context: .
          file: ./docker/bot.Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/taumer/mafia-bot:${{ env.SHA }}
            ghcr.io/taumer/mafia-bot:latest

  docker-web:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: DiscordMafia

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        id: builder-bot

      - uses: docker/setup-buildx-action@v3
        id: builder-web

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get SHA hash
        uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Build and upload image
        uses: docker/build-push-action@v5.1.0
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          builder: ${{ steps.builder-web.outputs.name }}
          context: .
          file: ./docker/web.Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/taumer/mafia-web:${{ env.SHA }}
            ghcr.io/taumer/mafia-web:latest