name: Build image

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: builder-bot

      - uses: docker/setup-buildx-action@v1
        id: builder-web

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get SHA hash
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Build bot
        uses: docker/build-push-action@v2
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          builder: ${{ steps.builder-bot.outputs.name }}
          context: .
          target: bot
          push: true
          tags: |
            taumer943/mafia-bot:${{ env.SHA }}
            taumer943/mafia-bot:latest

      - name: Build mafia
        uses: docker/build-push-action@v2
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          builder: ${{ steps.builder-web.outputs.name }}
          context: .
          target: web
          push: true
          tags: |
            taumer943/mafia-web:${{ env.SHA }}
            taumer943/mafia-web:latest