name: Build binaries

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 14.15.x

    - name: Install bower
      run: npm install -g bower
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --no-restore -c Release -o ${{ github.workspace }}/publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.0
      with: 
        name: DiscordMafia
        path: ${{ github.workspace }}/publish

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: DiscordMafia

    - name: Create archive
      uses: TheDoctor0/zip-release@0.4.1
      with: 
        path: DiscordMafia
        filename: DiscordMafia.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: DiscordMafia.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
