name: Build binaries

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 16

    - name: Install bower
      run: npm install -g bower
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 3.1.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --no-restore -c Release -o ${{ github.workspace }}/publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.3
      with: 
        name: DiscordMafia
        path: ${{ github.workspace }}/publish

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: DiscordMafia

    - name: Create archive
      uses: TheDoctor0/zip-release@0.7.6
      with: 
        path: .
        filename: DiscordMafia.zip

    - name: Get SHA hash
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: release
      uses: softprops/action-gh-release@v2
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.SHA }}
        files: DiscordMafia.zip
